'use strict';
const STORAGE_KEY='clearnext.cards.v1';
const MAX_TEXT=12000, MAX_FILE=500000, MAX_CARDS=100, MAX_STATE=250000;
const samples={utility:'Your electricity statement is ready. The amount due is $86.40 and payment is due on October 18, 2026. Please pay through your usual provider account. If you have already paid, no action is needed.',school:'Reminder: the permission form for the Year 6 museum visit must be returned to the school office by September 22, 2026. The visit is on October 3. Contact the school office if your child needs access support.',renewal:'Your home contents insurance policy will renew on November 12, 2026. The renewal price is $214. Please review the cover and contact your insurer before the renewal date if anything has changed.'};
const $=s=>document.querySelector(s); const text=$('#sourceText'), status=$('#status'), cardsEl=$('#cards');
function uid(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function bounded(s,n){return typeof s==='string'?s.slice(0,n):''}
function validCard(c){return c&&typeof c==='object'&&typeof c.id==='string'&&c.id.length>0&&c.id.length<=100&&typeof c.title==='string'&&c.title.length<=120&&typeof c.summary==='string'&&c.summary.length<=320&&typeof c.next==='string'&&c.next.length<=500&&typeof c.source==='string'&&c.source.length<=500&&c.date&&typeof c.date.value==='string'&&c.date.value.length<=100&&(c.date.certainty==='found'||c.date.certainty==='relative'||c.date.certainty==='none')}
function normalizeCard(c){return {id:bounded(c.id,100),title:bounded(c.title,120),summary:bounded(c.summary,320),next:bounded(c.next,500),source:bounded(c.source,500),date:{value:bounded(c.date.value,100),certainty:c.date.certainty},createdAt:bounded(c.createdAt||'',40)}}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY)||'[]';if(raw.length>MAX_STATE) return [];const value=JSON.parse(raw);if(!Array.isArray(value))return [];const seen=new Set();return value.filter(validCard).filter(c=>{if(seen.has(c.id))return false;seen.add(c.id);return true}).slice(0,MAX_CARDS).map(normalizeCard)}catch{return []}}
let cards=load();
function save(){const raw=JSON.stringify(cards);if(raw.length>MAX_STATE){status.textContent='Cards could not be saved because the local limit was reached.';return false}try{localStorage.setItem(STORAGE_KEY,raw);render();return true}catch{status.textContent='Browser storage is unavailable or full. Export your cards or delete some.';return false}}
function extractDate(s){const absolute=[/\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2}(?:,\s*\d{4})?/i,/\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b/];for(const p of absolute){const m=s.match(p);if(m)return {value:m[0],certainty:'found'}}const relative=s.match(/\b(?:today|tomorrow|next week)\b/i);if(relative)return {value:relative[0],certainty:'relative'};return {value:'No date found',certainty:'none'}}
function sourceSentence(s,date){const sentences=s.split(/(?<=[.!?])\s+/);return bounded(sentences.find(x=>date.value!=='No date found'&&x.toLowerCase().includes(date.value.toLowerCase()))||sentences[0]||s,500)}
function inferTitle(s){const l=s.toLowerCase();if(/electric|utility|statement|amount due|payment/.test(l))return 'Payment or bill notice';if(/school|permission|child|museum|office/.test(l))return 'School or family notice';if(/renew|policy|insurance|subscription/.test(l))return 'Renewal or subscription notice';if(/appointment|clinic|doctor|visit/.test(l))return 'Appointment notice';return 'Everyday notice'}
function inferStep(s){const l=s.toLowerCase();if(/permission form|form .*return|must be returned/.test(l))return 'Complete and return the form before the date shown.';if(/renew|policy|subscription/.test(l))return 'Review the terms and price, then contact the provider if anything needs changing.';if(/payment|amount due|bill|statement/.test(l))return 'Check the amount against your records and pay through your usual trusted provider channel.';if(/appointment|visit|clinic/.test(l))return 'Add the appointment to your calendar and note any questions or access needs.';return 'Read the notice once more, identify the person or organisation involved, and choose the safest next action.'}
function makeCard(raw){const s=bounded(raw.trim().replace(/\s+/g,' '),MAX_TEXT);const date=extractDate(s);return {id:uid(),title:inferTitle(s),summary:bounded(s,320),next:inferStep(s),date,source:sourceSentence(s,date),createdAt:new Date().toISOString()}}
function el(tag,attrs={},value){const n=document.createElement(tag);Object.entries(attrs).forEach(([k,v])=>k==='class'?n.className=v:n.setAttribute(k,v));if(value!==undefined)n.textContent=value;return n}
function render(){ $('#cardCount').textContent=`${cards.length} saved`;cardsEl.replaceChildren();if(!cards.length){const e=el('div',{class:'empty-state'});e.append(el('div',{class:'empty-icon','aria-hidden':'true'},'✦'),el('h3',{},'Your next step will appear here'),el('p',{},'Start with an example or paste a notice. You can edit anything ClearNext finds.'));cardsEl.append(e);return}cards.forEach(c=>{const article=el('article',{class:'card'});article.dataset.id=c.id;const top=el('div',{class:'card-top'}),h=el('h3',{},c.title),badge=el('span',{class:`badge ${c.date.certainty==='none'?'none':'found'}`},c.date.certainty==='none'?'Date not found':c.date.certainty==='relative'?'Relative date':'Date found');top.append(h,badge);const next=el('div',{class:'next-step'});next.append(el('strong',{},'Your next step'),el('p',{},c.next));const details=el('details',{class:'source'}),summary=el('summary',{},'Show source sentence');details.append(summary,el('blockquote',{},c.source));const actions=el('div',{class:'card-actions'});[['print','Print'],['ics','Export date'],['edit','Edit'],['delete','Delete']].forEach(([action,label])=>{const b=el('button',{class:`action-button ${action==='print'?'primary-lite':''}`,type:'button'},label);b.dataset.action=action;b.setAttribute('aria-label',`${label} ${c.title}`);actions.append(b)});article.append(top,el('p',{class:'summary'},c.summary),next,el('p',{class:'small'},`${c.date.certainty==='none'?'No confirmed date':c.date.certainty==='relative'?'Relative date':'Possible date'}: ${c.date.value}`),details,actions);cardsEl.append(article)})}
function download(name,type,content){const a=el('a');const url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function doICS(c){if(c.date.certainty!=='found'){status.textContent='Only an exact date can be exported. Confirm the date against the original notice.';return}const parsed=new Date(c.date.value);if(Number.isNaN(parsed.getTime())){status.textContent='This date is unclear, so it was not exported. Confirm an exact date first.';return}const clean=v=>String(v).replace(/\\/g,'\\\\').replace(/[\r\n]/g,'\\n').replace(/[;,]/g,v=>`\\${v}`);download('clearnext-date.ics','text/calendar',`BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//ClearNext//EN\nBEGIN:VEVENT\nSUMMARY:${clean(c.title)}\nDESCRIPTION:${clean(c.next)}\nDTSTART;VALUE=DATE:${parsed.toISOString().slice(0,10).replaceAll('-','')}\nEND:VEVENT\nEND:VCALENDAR`);status.textContent='Calendar file downloaded. Check the date before relying on it.'}
function create(){const raw=text.value.trim();if(!raw){text.classList.add('invalid');status.textContent='Paste some text or choose an example first.';text.focus();return}if(cards.length>=MAX_CARDS){status.textContent='The saved-card limit is reached. Delete a card before adding another.';return}text.classList.remove('invalid');cards.unshift(makeCard(raw));if(save()){status.textContent='Card created. Check the date and wording before acting.';text.value='';$('.result-panel').scrollIntoView({behavior:'smooth',block:'start'})}}
$('.input-actions').addEventListener('click',e=>{if(e.target.closest('#makeCard'))create()});document.querySelectorAll('[data-sample]').forEach(b=>b.addEventListener('click',()=>{text.value=samples[b.dataset.sample];text.focus();status.textContent='Example loaded. Make any changes, then create your card.'}));
$('#fileInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>MAX_FILE){status.textContent='That file is larger than 500 KB. Choose a smaller text or HTML file.';e.target.value='';return}try{let value=await f.text();if(value.length>MAX_TEXT)value=value.slice(0,MAX_TEXT);if(/\.html?$/i.test(f.name)||f.type==='text/html'){const doc=new DOMParser().parseFromString(value,'text/html');value=doc.body?.textContent||''}text.value=bounded(value.replace(/\s+/g,' ').trim(),MAX_TEXT);status.textContent=`Loaded ${bounded(f.name,80)}. Review it before creating a card.`}catch{status.textContent='That file could not be read safely.'}e.target.value=''});
cardsEl.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const elCard=b.closest('.card'),c=cards.find(x=>x.id===elCard?.dataset.id);if(!c)return;const a=b.dataset.action;if(a==='delete'){cards=cards.filter(x=>x.id!==c.id);save();status.textContent='Card deleted.'}else if(a==='print'){window.print()}else if(a==='ics')doICS(c);else if(a==='edit'){const n=prompt('Edit the next step:',c.next);if(n!==null&&n.trim()&&n.length<=500){const previous=c.next;c.next=n.trim();if(save())status.textContent='Next step updated.';else{c.next=previous;render()}}else if(n!==null)status.textContent='The next step must be 1–500 characters.'}});
$('#clearAll').addEventListener('click',()=>{if(cards.length&&confirm('Delete all saved cards from this browser?')){cards=[];save();status.textContent='All cards deleted from this browser.'}});
$('#exportAll').addEventListener('click',()=>{download('clearnext-backup.json','application/json',JSON.stringify({app:'clearnext',version:1,exportedAt:new Date().toISOString(),cards},null,2));status.textContent='Backup downloaded. It may contain private text.'});
$('#importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>MAX_FILE){status.textContent='That backup is larger than 500 KB.';e.target.value='';return}try{const x=JSON.parse(await f.text());if(x?.app!=='clearnext'||x.version!==1||!Array.isArray(x.cards)||x.cards.length>MAX_CARDS||new Set(x.cards.map(c=>c?.id)).size!==x.cards.length||!x.cards.every(validCard))throw Error();const imported=x.cards.map(normalizeCard);if(JSON.stringify(imported).length>MAX_STATE)throw Error();const previous=cards;cards=imported;if(save())status.textContent='Backup imported. Review dates before acting.';else{cards=previous;render();throw Error()}}catch{status.textContent='That backup could not be imported safely; existing cards were kept.'}e.target.value=''});
render();
